# Generated by Django 5.2.7 on 2025-11-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField()),
                ('id_doctor', models.IntegerField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
