# Generated by Django 5.2.7 on 2025-11-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_expedientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notamedica',
            old_name='id_paciente',
            new_name='nss_paciente',
        ),
    ]
